name: "Set Issue Label"
on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Amwam/issue-comment-action@v1.5.0
        with:
          keywords: '["from Backlog to Prioritized"]'
          labels: '["prioritized"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
