name: "Set Issue Label"
on:
  issue_comment:
    types: [created]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: contains(github.event.comment.body, 'from Backlog to Prioritized')
    steps:
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          LABELS: prioritized
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
